# Generated by Django 4.2.3 on 2023-08-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('verified_status', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateTimeField()),
                ('role', models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller'), ('admin', 'admin')], max_length=10)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_id', models.CharField(blank=True, max_length=100, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_type', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True)),
                ('social_media_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
