# Generated by Django 4.2.3 on 2023-08-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('colour', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
    ]
