# Generated by Django 4.2.3 on 2023-08-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verified_status',
        ),
    ]
