# Generated by Django 4.2.3 on 2023-08-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'blank': 'Email address cannot be blank.', 'invalid': 'Enter a valid email address.', 'unique': 'This email address is already in use.'}, max_length=254, unique=True),
        ),
    ]
